# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 11:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserMaps',
            new_name='UserMap',
        ),
    ]
